// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Serverless 运行时通过 DATABASE_URL 使用 Neon pooled endpoint；迁移等 CLI
// 操作优先走 DIRECT_URL。Docker/本地只配置 DATABASE_URL 时仍保持兼容。
const migrationDatabaseUrl =
  process.env.DIRECT_URL?.trim() || process.env.DATABASE_URL?.trim() || "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx ./prisma/seed.ts",
  },
  datasource: {
    url: migrationDatabaseUrl,
  },
});
